"""Generates $PORT_DIR/src/native/projection_regs.inc from the shader catalog:
the PS float-constant register holding g_mProjectionToWorld (the game's
inverse view-projection, 4 rows) for every pixel shader that declares it.
The native renderer reads the current camera from those constants (SSAO).
usage: python tools/shaders/gen_projection_regs.py"""
import json
import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
catalog = json.load(open(os.path.join(ROOT, 'artifacts', 'shaders', 'catalog.json')))['shaders']
rows = []
for e in catalog:
    if e['type'] != 'ps':
        continue
    for k in e['reflection'].get('constants', []):
        if k['name'] == 'g_mProjectionToWorld' and k['rows'] == 4 and k['cols'] == 4:
            rows.append((int(e['container_hash'], 16), k['reg']))
rows.sort()
sys.path.insert(0, os.path.join(ROOT, 'tools'))
from kitcfg import PORT  # noqa: E402
out = os.path.join(PORT, 'src', 'native', 'projection_regs.inc')
with open(out, 'w', newline='\n') as f:
    f.write('// Generated by tools/shaders/gen_projection_regs.py - do not edit.\n')
    f.write('// {pixel shader hash, PS constant register of g_mProjectionToWorld}\n')
    for h, reg in rows:
        f.write(f'{{0x{h:016X}ull, {reg}}},\n')
print(f'{len(rows)} shaders -> {out}')
