"""Decode the XDK D3D render-state / sampler-state dispatch template tables in the
Conan image (found at 0x82A0A284 / 0x82A0A6C8) and print name -> setter/getter/default."""
import struct
from disdb import DB, BASE
RS = """ZENABLE ZFUNC ZWRITEENABLE FILLMODE CULLMODE ALPHABLENDENABLE SEPARATEALPHABLENDENABLE BLENDFACTOR
SRCBLEND DESTBLEND BLENDOP SRCBLENDALPHA DESTBLENDALPHA BLENDOPALPHA ALPHATESTENABLE ALPHAREF ALPHAFUNC
STENCILENABLE TWOSIDEDSTENCILMODE STENCILFAIL STENCILZFAIL STENCILPASS STENCILFUNC STENCILREF STENCILMASK
STENCILWRITEMASK CCW_STENCILFAIL CCW_STENCILZFAIL CCW_STENCILPASS CCW_STENCILFUNC CCW_STENCILREF CCW_STENCILMASK
CCW_STENCILWRITEMASK CLIPPLANEENABLE POINTSIZE POINTSIZE_MIN POINTSPRITEENABLE POINTSIZE_MAX MULTISAMPLEANTIALIAS
MULTISAMPLEMASK SCISSORTESTENABLE SLOPESCALEDEPTHBIAS DEPTHBIAS COLORWRITEENABLE COLORWRITEENABLE1 COLORWRITEENABLE2
COLORWRITEENABLE3 TESSELLATIONMODE MINTESSELLATIONLEVEL MAXTESSELLATIONLEVEL WRAP0 WRAP1 WRAP2 WRAP3 WRAP4 WRAP5
WRAP6 WRAP7 WRAP8 WRAP9 WRAP10 WRAP11 WRAP12 WRAP13 WRAP14 WRAP15 VIEWPORTENABLE HIGHPRECISIONBLENDENABLE
HIGHPRECISIONBLENDENABLE1 HIGHPRECISIONBLENDENABLE2 HIGHPRECISIONBLENDENABLE3 HALFPIXELOFFSET PRIMITIVERESETENABLE
PRIMITIVERESETINDEX ALPHATOMASKENABLE ALPHATOMASKOFFSETS GUARDBAND_X GUARDBAND_Y DISCARDBAND_X DISCARDBAND_Y
HISTENCILENABLE HISTENCILWRITEENABLE HISTENCILFUNC HISTENCILREF PRESENTINTERVAL PRESENTIMMEDIATETHRESHOLD
HIZENABLE HIZWRITEENABLE LASTPIXEL LINEWIDTH BUFFER2FRAMES""".split()
SS = """ADDRESSU ADDRESSV ADDRESSW BORDERCOLOR MAGFILTER MINFILTER MIPFILTER MIPMAPLODBIAS MAXMIPLEVEL MAXANISOTROPY
MAGFILTERZ MINFILTERZ SEPARATEZFILTERENABLE MINMIPLEVEL TRILINEARTHRESHOLD ANISOTROPYBIAS HGRADIENTEXPBIAS
VGRADIENTEXPBIAS WHITEBORDERCOLORW POINTBORDERENABLE""".split()
RS_TABLE, SS_TABLE = 0x82A0A280, 0x82A0A6C8  # {Get,Set,Default}; RS table really starts 10 no-op rows earlier at 0x82A0A208
RS_BASE_INDEX = 10  # D3DRS_ZENABLE == 40 in this XDK; device dispatch = dev+0x40+4*(D3DRS/4)
def load():
    db = DB.load(); img = db.image(); out = {}
    for i, n in enumerate(RS):
        g, s, d = struct.unpack_from('>III', img, RS_TABLE + 12 * i - BASE)
        out[s] = ('D3DDevice_SetRenderState_' + n, 'D3DRS_%s=%d default=0x%08X get=%08X' % (n, (i + RS_BASE_INDEX) * 4, d, g))
        out.setdefault(g, ('D3DDevice_GetRenderState_' + n, ''))
    for i, n in enumerate(SS):
        g, s, d = struct.unpack_from('>III', img, SS_TABLE + 12 * i - BASE)
        out[s] = ('D3DDevice_SetSamplerState_' + n, 'D3DSAMP_%s=%d default=0x%08X get=%08X' % (n, i * 4, d, g))
        out.setdefault(g, ('D3DDevice_GetSamplerState_' + n, ''))
    return out
if __name__ == '__main__':
    db = DB.load(); c = db.calls(); t = load()
    print(len(RS), 'render states', len(SS), 'sampler states')
    for a, (n, info) in sorted(t.items(), key=lambda x: x[0]):
        if 'Set' in n:
            print('%08X %-50s callers=%3d %s' % (a, n, len(c.get(a, [])), info))
